version: '3'

services:
  api:
    container_name: api
    build: './api-server'
    restart: always
    command: npm start
    volumes:
      - ./api-server:/usr/app
    ports:
      - '3000:3000'
    env_file:
      - ./api-server/.env
    depends_on:
      - db

  db:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'